apiVersion: apps/v1
kind: Deployment

metadata:
  name: java-shopping

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: java-shopping

  template:
    metadata:
      labels:
        app: java-shopping

    spec:
      containers:
        - name: java-shopping
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 8080
