- name: Deploy Java Shopping Application
  hosts: app_servers
  become: true

  roles: 
    - java_app

  vars_files:
    - vars.yml

  tasks:

    - name: Show deployment values
      debug:
        msg:
          - "AWS Region: {{ aws_region }}"
          - "ECR Image: {{ ecr_image }}"
          - "Container Name: {{ container_name }}"
          - "Port: {{ host_port }}:{{ container_port }}"

    - name: Login to Amazon ECR
      shell: |
        aws ecr get-login-password --region {{ aws_region }} |
        docker login --username AWS --password-stdin {{ ecr_registry }}

    - name: Pull Java Shopping Docker image
      community.docker.docker_image:
        name: "{{ ecr_image }}"

        source: pull

      
    - name: Deploy and verify new version
      block:

        - name: Run Java Shopping container
          community.docker.docker_container:
            name: "{{ container_name }}"
            image: "{{ ecr_image }}"
            state: started
            restart: true
            recreate: true
            ports:
              - "{{ host_port }}:{{ container_port }}"

        - name: Check Java Shopping application health
          uri:
            url: "http://localhost:{{ host_port }}/health"
            status_code: 200
            return_content: true

        - name: Display application health
          debug:
            msg: "Application health: UP"

      rescue:

        - name: Rollback to previous Docker image
          community.docker.docker_container:
            name: "{{ container_name }}"
            image: "{{ ecr_registry }}/java-shopping-name:{{ previous_image_tag }}"
            state: started
            restart: true
            recreate: true
            ports:
              - "{{ host_port }}:{{ container_port }}"

        - name: Check application health after rollback
          uri:
            url: "http://localhost:{{ host_port }}/health"
            status_code: 200
            return_content: true
          register: rollback_health

        - name: Display rollback health
          debug:
            msg: "Rollback application health: {{ rollback_health.content }}"

