aws_region: "ap-south-1"

ecr_registry: "536697229262.dkr.ecr.ap-south-1.amazonaws.com"

image_tag: "latest"

ecr_image: "536697229262.dkr.ecr.ap-south-1.amazonaws.com/java-shopping-name:{{ image_tag }}"

container_name: "java-shopping-container"

host_port: 80

container_port: 8080
